name: grad_project
description: A simple simulation for a block chain node
version: 1.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  args: ^2.3.0
  build_runner: ^2.1.8
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  lints: ^1.0.0
  uuid: ^3.0.6
dependencies: 
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  rxdart: ^0.27.3
